### ISSUE TITLE
Resolve "OpenFn job state warning: large file size" warning for "1. Get Cases from Primero" job

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#11]
## Describe the bug

The only thing that should be retained in this timer job’s state is the cursor. It looks like it’s saving other data in memory which is why this alert is coming up. 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/80456839/197284814-30509bd0-e48a-4dab-b2a3-ad1dda7621cc.png">

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/getCasesFromPrimero.js

### state.json

```json
{
  "configuration": ["SEE LAST PASS: 'Primero V2 Cambodia Demo (API user)'"],
  "cursor": "USE THE CURSOR CURRENTLY IN JOB"
}
```

**Comment by taylordowns2000** [comment]
@aleksa-krolls , @daissatou2 , two questions here:

1. do you have evidence that the state is _growing_ or just that it's big? if it's big, let's not do anything at all. if it's _growing_ each time it runs, then let's try to refactor.

2. Re: "The only thing that should be retained in this timer job’s state is the cursor" - I could be misunderstanding the flow, but I don't think that's right. I think you need to save a whole bunch of `cases` to state so that you can use a flow-triggered job which runs immediately after this one. Is that right?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @mtuchi to recap our call...
1. Yes, we expect there to be 1000+ cases in prod. And it will grow each year, and we plan to run it annually at the end of the year to sync key indicator data to the ONA DB.  
2. This is a flow job (bc we don't want to write data to OpenFn servers for UNICEF), so we will need to figure out how to bulkify this. FYI, it looks like [the current job](https://www.openfn.org/projects/primero-ona-cambodia-io-staging/jobs/eAe1lX) has a pretty large parameter `per: 100000000`. 

Perhaps we could rather split this into multiple requests and make use of paging, so pls explore the [Primero API docs](https://github.com/primeroIMS/primero/blob/development_v2/app/controllers/api/v2/docs/cases/get.md) and test accordingly. If we're finding that ~1000 records = approx 5.5 MB, then maybe we could query only 1k at a time (e.g., `per: 1000`) and then use paging to determine how many additional requests we need to send. 

Happy for you to suggest an approach so long as all data can be synced and _not_ persisted on our servers.

**Comment by daissatou2** [comment]
@mtuchi **per our brainstorming session with Taylor, let's update this flow to have 4 jobs instead of 2.** There will be 2 new jobs that will post metadata about paging to the OpenFn inbox. These messages will trigger job 1 (Get Primero Cases). 

**Job 0 (new):** Cron job that will be scheduled to run on the 1st day of each year which will kick off the sync. This job will post this [sample payload](https://github.com/OpenFn/primero-ona-dashboard/blob/main/sampleData/job0_sample_payload.json) to the project OpenFn inbox. 


**[Job 1](https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/getCasesFromPrimero.js):** Message filter job which will fetch cases from Primero (maintain the existing criteria for fetching cases) using the metadata in the message which triggered the job. For example: The first time it runs it will be triggered by Job 0 and fetch data using `page` = 1, `per`= 500. The second time it runs it will be triggered by Job 3 and fetch data using `page` = 2, `per` = 500. This flow will continue until we have fetched and synced data for all pages.

**[Job 2](https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js):** Flow job which will transform and load the data retrieved from Job 1 to the ONA database. 

**Job 3 (new):** Flow job which will POST a message to the OpenFn inbox. See sample [payload](https://github.com/OpenFn/primero-ona-dashboard/blob/main/sampleData/job0_sample_payload.json). The `page` in this payload should be the current `page`+1. 



**See Taylor's data flow diagram below for details about how each job will use the `page` and `per` metadata to ensure that all Primero data is fetched and synced to the database in batches.** 
![image](https://user-images.githubusercontent.com/80456839/197590258-82ebbfdb-0b14-429a-ad34-0c94db76da47.png)

**Comment by mtuchi** [comment]
@aleksa-krolls 
currently testing this on `platform-app`, I should be able to finish this early morning tomorrow, but so far so good
Just couple of twist to make the flow behave the way it's suppose to behave 

cc @daissatou2

**Comment by aleksa-krolls** [comment]
@mtuchi as discussed on Slack, right now if there are only 2 GET requests to send to Primero, 3 Messages are still sent to the OpenFn Inbox. It would be great if for every GET request, 1 message is sent to Inbox... and if no more data to get, then let's stop the flow and _not_ send another Message to Inbox. Otherwise I think this will be confusing to the admin. 

<img width="1162" alt="Screen Shot 2022-10-26 at 2 19 19 PM" src="https://user-images.githubusercontent.com/16758106/198014299-5bacf9e2-4df4-4afb-8062-c8ab9a78c280.png">

**Comment by mtuchi** [comment]
> @mtuchi as discussed on Slack, right now if there are only 2 GET requests to send to Primero, 3 Messages are still sent to the OpenFn Inbox. It would be great if for every GET request, 1 message is sent to Inbox... and if no more data to get, then let's stop the flow and _not_ send another Message to Inbox. Otherwise I think this will be confusing to the admin.
> 
> <img alt="Screen Shot 2022-10-26 at 2 19 19 PM" width="1162" src="https://user-images.githubusercontent.com/16758106/198014299-5bacf9e2-4df4-4afb-8062-c8ab9a78c280.png">

@aleksa-krolls this is worked on and fixed. You can proceed to test on `platform-app`

**Comment by aleksa-krolls** [comment]
@mtuchi looking good, closing now. Thank you!
