### ISSUE TITLE
Oban error on Job 3: Request next batch

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#22]
## Describe the bug
I am seeing the error below for [Job 3: Request next batch]( https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/3-request-next-batch.json). This error usually means that we are attempting to pass too much data from job 2 to job 3.

```
OpenFn encountered an unexpected error during the execution of this job:
%Oban.CrashError{
  message: "** (throw) \"Killing run before execution; artifacts @\\\"10.577\\\"MB\"",
  reason: "Killing run before execution; artifacts @\"10.577\"MB"
}
```
By this third job, all data has already been loaded into the database. The data that is being passed to job 3 should only be what's essential for requesting the next batch (i.e. metadata). Please remove any irrelevant data from Job 2's final state before passing it to Job 3.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/primero-ona-cambodia-io-prod/runs/064e5f17-7a6f-7546-a2ce-bc68d229d6cd

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/3-request-next-batch.json

### state.json

Job 0: 
{"inboxUrl":"ADD URL"}

Job 1:
```json
{
  "configuration": ["SEE LAST PASS: 'Primero Cambodia V2 Demo (api_user)'"],
  "data": {"NA" },
  "cursor": "2023-01-01T00:00:00.000Z"
}
```

Job 2:
```json
{
  "configuration": ["SEE LAST PASS: 'ONA Test Database'"],
  "data": {"NA" },
  "cursor": "2023-01-01T00:00:00.000Z"
}
```

Job 3:
{"inboxUrl":"ADD URL"}

## Expected behavior
The job should sucessfully run and post a  message to the inbox.

## To test/resolve
1. Make your changes on a separate branch from staging.
2. After the desired output is working locally (from the CLI), please [open a pull request] and I will merge to the staging branch.
3. [Please test the change on OpenFn.org by re-running Job 0. Initate Sync with a cursor date of `2020-01-01T06:55:31.494Z`

**Comment by mtuchi** [comment]
@daissatou2 I have provided a fix in this PR #23 , and tested the workflow on staging, [See activity history](https://www.openfn.org/projects/primero-ona-cambodia-io-staging/runs/064e7673-419e-7023-8305-913a64ea6f93)
