### ISSUE TITLE
Getting data from Primero to load to ONA Database 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#4]
# Feature Request 

## Background, context, and business value
OpenFn will check Primero for data once every year in order to extract indicator results that will be reported on and visualized in an external DB. 

Create Jobs 1 & 2 in which OpenFn gets cases and services from Primero, maps the Primero extract and upserts to the ONA Postgres database.

1. Get referral data twice (there are two Primero indicators): 
- `GET /api/v2/cases` -- where "type_of_case" =  "Children Undergoing Reintegration"
- `GET /api/v2/cases` -- where where Age < 18 years
- Sample response: Primero responds with list of cases (example response: [list_cases_primero.json](https://github.com/OpenFn/unicef/blob/master/sample_data/list_cases_primero.json))
2. Map data to ONA database using mapping [sheet](https://docs.google.com/spreadsheets/d/1mDMpH87JWPqPXMNTIXMFl0Uxu2yCPWI5tzuhCcexPIg/edit#gid=990515176) under the "Mapping to DB" tabs
4. Upsert cases and referrals in ONA database

See data flow [diagram](https://lucid.app/lucidchart/f7f7607f-8cb0-46d3-b00a-a4171a5ee823/edit?invitationId=inv_dfb0977f-5c8b-48ed-9678-58e7016b795d&page=k9buV_utGYNG#).

## state.json
Job 1: Get cases from Primero

```json
{
  "configuration": ["SEE LAST PASS: 'Primero V2 Cambodia Demo"],
  "data": {"data will be generated from GET request"},
  "cursor": "cases created_at > cursorDateTimeYearStart && cases created_at < cursorDateTimeYearEnd"
}
```
Example for the cursor above: If the job cron trigger runs on `Jan 1, 2022`, we want to GET cases that would have been created before `Jan 1, 2022` but after `Jan 1, 2021`.

Job 2: Load to DB

```json
{
  "configuration": ["SEE LAST PASS: 'ONA Test Database"],
  "data": {"data will be generated from GET request"},
}
```

## adaptor
Primero 
PostgreSQL

## expression.js
2 new jobs to create in a new `dashboard` directory in this repo. 
1. GET cases from Primero
2. Map Primero response and upload to ONA database 

### trigger
1. Cron timer
2. Flow jobs

**Comment by elias-ba** [comment]
@daissatou2 this is now done and ready for testing. Let me know for any feed-back.
