### ISSUE TITLE
Primero data not being properly loaded into ONA database

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#5]
## Describe the bug
When I run [`Flow 1-1 Get Cases from Primero`](https://github.com/OpenFn/primero-ona-dashboard/blob/main//jobs/getCasesFromPrimero.js) it retrieves some data from Primero. However after the [`Flow 1-2 Send Cases to ONA`](https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js) job runs and I check out the database, all the columns except `case_source` are empty for every row in the `cases` table. The `services` table is also empty. 

![image](https://user-images.githubusercontent.com/80456839/148053998-59ea777b-c36b-4e75-b23b-5d68d41dde93.png)

## To Reproduce
1. Reset the ONA database by running this job: https://www.openfn.org/projects/primero-ona-cambodia-io/jobs/FqEPEW
2. Run F1-1: https://www.openfn.org/projects/primero-ona-cambodia-io/jobs/eAe1lX. Use the state from F1-1 to run F1-2. (If you are testing on platform this second job will run automatically).
3. Check out the results in the ONA database using LP credential `ONA Test Database`. Make sure you are connected to the OpenFn VPN. 

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js

### state.json
```json
{
  "configuration": ["SEE LAST PASS: 'ONA Test Database'"],
  "data": { Run Flow 1-1 to generate state},
}
```

## Expected behavior
The rows in the database should not be empty in both the `cases` and `services` tables. It should contain the data that was retrieved from the F1-1 run which fetches Primero cases and services. 

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by using the 3 steps outlined above.]

**Comment by elias-ba** [comment]
@daissatou2 this is now solved and is working fine.

See attached screenshot ![Screenshot from 2022-01-04 16-37-19.png](https://images.zenhubusercontent.com/613b27c26d31a577b1526ccc/9a182840-2ab2-4794-bd77-98f459c65269).

Please do your tests and close this issue if everything fine otherwise let me know.

**Comment by daissatou2** [comment]
@elias-ba moving this back to the backlog because of two issues:
1. The `services` table is still empty after running those two jobs. I know at least some of the cases do have services in Primero. Case with `case_id` = "322cbca" does have services, for example.
![image](https://user-images.githubusercontent.com/80456839/148100975-3c5ffebc-ead6-45b9-8df5-15183ed13112.png)
2. The `protection_concerns` column on `cases` is empty for all rows. For example, case with `case_id` = "322cbca" does have a protection concern but this not reflected in the database.

**Comment by elias-ba** [comment]
@daissatou2 was this clearly stated in [this issue](https://app.zenhub.com/workspaces/implementation-engineering-600030af88f2bb00155d46a5/issues/openfn/primero-ona-dashboard/4) ? Are these values (protection_concerns and services) in [this mapping](https://docs.google.com/spreadsheets/d/1mDMpH87JWPqPXMNTIXMFl0Uxu2yCPWI5tzuhCcexPIg/edit#gid=990515176) ? In [this job expression](https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js) there's no mapping that takes in account of `protection_concerns` and `services`, I don't think we implemented that. Is it a new feature or did we miss it ?

**Comment by daissatou2** [comment]
@elias-ba Yes, it's in there and also mentioned in this issue. Please review the mappings and the issues and let me know if any questions.

**Comment by elias-ba** [comment]
Okay @daissatou2, let me check that quickly and come back to you.

**Comment by elias-ba** [comment]
Hey @aissatou which is the right mapping to use ? 4.8 or 4.11a or both ?

**Comment by daissatou2** [comment]
@elias-ba Both. There are two primero indicators: 4.8 & 4.11a. Let me know if a call is helpful but all the original info is here: https://app.zenhub.com/workspaces/implementation-engineering-600030af88f2bb00155d46a5/issues/openfn/primero-ona-dashboard/4

**Comment by elias-ba** [comment]
@daissatou2 in the mapping 4.11a the `protection_concerns` field is described as a string field while in the state it's an array of strings. Is there any transformation needed or do we just send the array of strings like that ?

**Comment by elias-ba** [comment]
@daissatou2 the column `service_date` contains the value `not_implemented` instead of a date. How can we handle that ?

**Comment by elias-ba** [comment]
I am currently skipping that column in the mapping.

**Comment by elias-ba** [comment]
@daissatou2 this is now done. The services table is now being populated for each case. See screenshots attached. Please test it and lmk.

![Screenshot from 2022-01-05 15-07-57](https://user-images.githubusercontent.com/86059666/148240390-14c93c62-e2a2-4252-8bb3-7180e3fec6ac.png)

![Screenshot from 2022-01-05 15-08-16](https://user-images.githubusercontent.com/86059666/148240406-a0221274-764f-4079-a8bc-0f4b6dff8fbe.png)

**Comment by aleksa-krolls** [comment]
@daissatou2 How is this looking? Please close out the issue if tests are passing on your side, or feel free to move to backlog if changes required.
