### ISSUE TITLE
Implement updated mappings for the `province` and `district` fields in the db

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#6]
## Background, context, and business value

We have received new mapping logic for the `province` and `district` fields in the db. They are highlighted in yellow [here](https://docs.google.com/spreadsheets/d/1mDMpH87JWPqPXMNTIXMFl0Uxu2yCPWI5tzuhCcexPIg/edit#gid=2050490642). Update the mappings in the [upsertCasesToONA job](https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js).

There will now be 4 locations fields in the database: `province_current`, `district_current`, `province_caregiver`, `district_caregiver`. This data will come from the `location_current` and the `location_caregiver` fields in Primero. 

## state.json
{
  "configuration": ["SEE LAST PASS: 'ONA Test Database"],
  "data": {"data will be generated from GET request"},
}

**Comment by lakhassane** [comment]
@daissatou2 let's discuss this on Monday. I lack a bit of context and don't quite understand what you mean by checking source value to search a table.
Do you mean we should fetch a table before doing the upsert to check those values?

**Comment by daissatou2** [comment]
@lakhassane sure we can discuss when you're back. But here's an example for you: 
if we receive "53098" in the message for `location_current` or `location_caregiver`, we want to search the `locations_lookup` table in the database. This table has a column called `code`. 

So search in `locations_lookup`  to find the row where `code` == 53098. Depending on the field you're mapping, return the `province` or `district` for that row. 

Aleksa and I tried implementing it using the [findValue()](https://github.com/OpenFn/language-postgresql#find-a-single-value-for-a-table) function. But we are seeing bracket errors show up in the platform before saving:
![image](https://user-images.githubusercontent.com/80456839/152788402-51e1417a-1425-4970-b624-a22a7bd2bd13.png)

**Comment by lakhassane** [comment]
@daissatou2 could you clarify which column from `locations_lookup` to check. the snippet you added says `location_code` while in the issue it is `code`. I checked and neither of them exist in that table

**Comment by lakhassane** [comment]
@daissatou2 I added the new mappings. it's ready for testing
