### ISSUE TITLE
Add mappings for `protection_concerns` to the upsertcasestoONA job

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#7]
## Background, context, and business value

We have received feedback from the ONA team that it would be helpful to see the front-end labels for protection concerns instead of the db values.

## The specific request, in as few words as possible
I have created this [mapping table](https://docs.google.com/spreadsheets/d/1mDMpH87JWPqPXMNTIXMFl0Uxu2yCPWI5tzuhCcexPIg/edit#gid=900816024&range=A1) which needs to be added to the [upsertcasestoONA job](https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js). 

For each for row in the mappings: 
- the value in the `db value` column is what we receive from Primero for the `protection_concerns` field
- the value in the  `Primero label (value that OpenFn sends to ONA)` column is what we need to send to the ONA database for the `protection_concerns` column. 

Ex. if we receive `disabled` from Primero, we should send `At risk of neglect` to the ONA database. 

**Note: we receive `protections_concerns` as an array that can have 0 or more items. Continue to send these to ONA by separating each one with a comma. (This is the current implementation).** 

## state.json
{
"configuration": ["SEE LAST PASS: 'ONA Test Database"],
"data": {"data will be generated from GET request"},
}

**Comment by aleksa-krolls** [comment]
@daissatou2 I added a placeholder for the mappings, that Mamadou will apply to each `protection_concern` value provided. Can you go ahead and please add in the rest of the mappings from the Excel sheet for him?  
https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js#L3

**Comment by daissatou2** [comment]
I have added the entire protection map to the Job : https://github.com/OpenFn/primero-ona-dashboard/commit/6ef997ca595c89ad8e8cc36ed81e84017017e368

**Comment by lakhassane** [comment]
@daissatou2 I added a snippet to relabel protection concern.
I made tests on platform to confirm green check. Could you check the front to see if everything is ok: https://www.openfn.org/projects/primero-ona-cambodia-io/runs/06202ae2-dc46-7240-b9ed-2494fddb172a

**Comment by daissatou2** [comment]
looks great!
