### ISSUE TITLE
Add mappings for several fields to the upsertcasestoONA job

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-ona-dashboard#8]
## Background, context, and business value

We have received feedback from the Primero team that it would be helpful to see the front-end labels for the fields below instead of the DB values that we currently send.  

`sex` 
`services_section[].service_type` 
`disability_type`

## The specific request, in as few words as possible

1. Use the [mapping tables](https://docs.google.com/spreadsheets/d/1mDMpH87JWPqPXMNTIXMFl0Uxu2yCPWI5tzuhCcexPIg/edit#gid=1518685045&range=A1) for `services_section[].service_type` and `disability_type`. 

For each for row in the mappings:
- the value in the `db value` column is what we receive from Primero for these fields
- the value in the `Primero label (value that OpenFn sends to ONA)` column is what we need to send to the ONA database for the mapped columns

Ex. if we receive `disability_type = "both"` from Primero, we should send `"Hearing or Speech Disability"` to the ONA database.

2. Add a transformation for `sex` using the mappings [here](https://docs.google.com/spreadsheets/d/1mDMpH87JWPqPXMNTIXMFl0Uxu2yCPWI5tzuhCcexPIg/edit#gid=2050490642&range=K7). 

## state.json

Fetch data from Primero
{
  "configuration": ["SEE LAST PASS: 'Primero V2 Cambodia Demo"],
  "data": {"data will be generated from this GET request"},
}

Loading data to ONA DB
{
"configuration": ["SEE LAST PASS: 'ONA Test Database"],
"data": {"data will be generated from the GET request above"},
}

**Comment by daissatou2** [comment]
@lakhassane @grayey please implement these changes but **hold off on testing.** Primero has revoked our user access until they complete their data migration. Once they give us the green light, we'll be able to test our changes.

**Comment by lakhassane** [comment]
@daissatou2 I made the mappings for the fields.

@grayey feel free to check the commit for context on what was done

**Comment by aleksa-krolls** [comment]
@daissatou2 if this is tested, can we please close this? Thanks!

**Comment by daissatou2** [comment]
won't be able to test until our ONA db access issue is resolved.
