### ISSUE TITLE
Performance issues: job timing out when loading data to DB

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-ona-dashboard#9]
## Describe the bug
For UNICEF Cambodia, [in this project](https://www.openfn.org/projects/primero-ona-cambodia-io-staging/jobs) we have a flow that extracts data from Primero, maps, and loads it into a postgres DB, which is connected to a dashboard for reporting on key indicators. 
<img width="836" alt="Screen Shot 2022-10-21 at 7 28 41 AM" src="https://user-images.githubusercontent.com/16758106/197112295-b3b3ccb9-e50a-4698-90c4-8d4129307f41.png">

In recent tests, the load step is timing out: https://www.openfn.org/projects/primero-ona-cambodia-io-staging/runs/06352170-6fe1-7c1d-9a76-3ff53f691652

I suspect this is because we are do a series of steps **for each case**, but we should rather try to load data in bulk to the DB. 
https://github.com/OpenFn/primero-ona-dashboard/blob/a7bbf48b01d2d98fd87c82d763339181d9a534c8/jobs/upsertCasesToONA.js#L89-L90

## To Reproduce
1. Re-run Job1 `language-primero v2.3.5`: https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/getCasesFromPrimero.js
2. Use the final state from this^ to run Job2

### expression.js
Job 2: https://github.com/OpenFn/primero-ona-dashboard/blob/main/jobs/upsertCasesToONA.js
`language-postgres`

### state.json
Job1: 
```json
{
  "configuration": ["SEE LAST PASS: 'Primero V2 Cambodia Demo (api_user)'"],
  "data": { }
}
```

Job2: 
***Use the OpenFn VPN/Wireguard to access this DB**
```json
{
  "configuration": ["SEE LAST PASS: 'ONA Test Database '"],
  "data": {"FINAL STATE FROM JOB 1"}
}
```

## Expected behavior
Load all the data extracted from the Primero app into the DB in one step to feed into connected dashboards.

**Comment by aleksa-krolls** [comment]
@mtuchi this is a sort of bug/enhancement request. Can you please check this out sometime today? 
@daissatou2 can help with any questions about the DB configuration. You can also use Wireguard to turn on the OpenFn VPN and then use a tool like DBeaver to explore the DB setup, if desired.

**Comment by mtuchi** [comment]
@daissatou2 this is ready to be tested see PR #10 , please make sure you update the `postgresql` to `@openfn/language-postgresql@3.4.0`

**Comment by daissatou2** [comment]
testing pending issue #11 .

**Comment by aleksa-krolls** [comment]
@mtuchi fyi I'm closing this one out because the sync is working well. There's just the small change I requested on #11 to limit how many Messages we send to the OpenFn Inbox.
